command: [
  "python",
  "app.py"
]

env:
  - name: "CATALOG_NAME"
    value: "mfg_mc_se_sa"
  - name: "SCHEMA_NAME"
    value: "zach_demo"
  - name: "DATABRICKS_WAREHOUSE_ID"
    valueFrom: "sql-warehouse"
  - name: "MAS_ENDPOINT"
    value: "mas-52b123a7-endpoint"
  - name: "USE_DATABASE"
    value: "true"
  - name: "LAKEBASE_DATABASE_NAME"
    value: "databricks_postgres"
  - name: "LAKEBASE_INSTANCE_NAME"
    value: "qbr-demo-instance"
  - name: "DATABRICKS_USER"
    value: "zach.jacobson@databricks.com"